import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WorkerService", targetNamespace = "default", wsdlLocation = "http://localhost:8080/services?wsdl")
public class WorkerService
    extends Service
{

    private final static URL WORKERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WORKERSERVICE_EXCEPTION;
    private final static QName WORKERSERVICE_QNAME = new QName("default", "WorkerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/services?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WORKERSERVICE_WSDL_LOCATION = url;
        WORKERSERVICE_EXCEPTION = e;
    }

    public WorkerService() {
        super(__getWsdlLocation(), WORKERSERVICE_QNAME);
    }

    public WorkerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WORKERSERVICE_QNAME, features);
    }

    public WorkerService(URL wsdlLocation) {
        super(wsdlLocation, WORKERSERVICE_QNAME);
    }

    public WorkerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WORKERSERVICE_QNAME, features);
    }

    public WorkerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Worker
     */
    @WebEndpoint(name = "WorkerPort")
    public Worker getWorkerPort() {
        return super.getPort(new QName("default", "WorkerPort"), Worker.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Worker
     */
    @WebEndpoint(name = "WorkerPort")
    public Worker getWorkerPort(WebServiceFeature... features) {
        return super.getPort(new QName("default", "WorkerPort"), Worker.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WORKERSERVICE_EXCEPTION!= null) {
            throw WORKERSERVICE_EXCEPTION;
        }
        return WORKERSERVICE_WSDL_LOCATION;
    }

}
